project:
  type: website
  resources:
    - fonts/*
  render: [index.qmd, page_*.qmd, "!page_demo.qmd"]

website:
  title: "CNC Austria 2026"
  search: false
  description: "Auswertungen und Analyse fÃ¼r die City Nature Challenge in Ã–sterreich."
  repo-url: "https://github.com/HannesOberreiter/city-nature-challenge-austria-2026"
  repo-actions: "edit"

  navbar:
    right:
      - icon: person-lines-fill
        text: ""
        file: page_about.qmd
      - icon: github
        href: "https://github.com/HannesOberreiter/city-nature-challenge-austria-2026"
    left:
      - file: index.qmd
        text: "Ãœbersicht"
      - text: "Regionen"
        menu:
          - file: page_steiermark.qmd
            text: "Steiermark"
          - href: page_salzburg.qmd
            text: "Salzburg"
          - href: page_vorarlberg.qmd
            text: "Vorarlberg"
      - text: "Analysen"
        menu:
          - file: page_primeval_forest_relict_beetle.qmd
            text: "UrwaltreliktkÃ¤fer"
          - href: https://hannesoberreiter.github.io/inat-austria-city-challenge-2025/
            text: "CNC 2025 ðŸ”—"
          - href: https://hannesoberreiter.github.io/inat-austria-city-challenge-2024/
            text: "CNC 2024 ðŸ”—"
          - href: https://hannesoberreiter.github.io/inat-austria-city-challenge-2023/
            text: "CNC 2023 ðŸ”—"
format:
  html:
    code-fold: true
    embed-resources: false
    include-in-header:
      - file: assets/customMetaTags.html
    link-external-icon: false
    theme:
      light: [flatly, assets/fonts.scss]
      dark: [darkly, assets/fonts.scss]
    css: assets/styles.css
    toc: true
